As it is known that exceptions allow an application to transfer control from one part of the code to another. When an exception is thrown, the current flow of the code is interrupted and handed back to a parent try catch block. In a try-finally situation, a try block is used to encapsulate a region of code. if any of the code throws an exception within that try block, the exception will be handled by the corresponding. The finally block allows you to execute certain code if an excpetion is thrown or not . For example, disposing of an object that must be disposed of.